"""
Official NY OCM Licensed Dispensaries
Source: https://data.ny.gov/Economic-Development/Current-OCM-Licenses/jskf-tt3q
Generated: 2026-01-13T20:34:38.981718
"""

NY_LICENSED_DISPENSARIES = [
    {"name": "SONIRUS ENTERPRISE LLC", "address": "78 SOUTHERN BLVD", "city": "ALBANY", "zip": "12209"},
    {"name": "296 Retail Venture LLC", "address": "296 Route 59", "city": "Airmont", "zip": "10901"},
    {"name": "7 Point Dispensary INC.", "address": "332 Northern Blvd", "city": "Albany", "zip": "12204"},
    {"name": "Crush New Scotland & Grove Dispensary", "address": "45 Grove Ave", "city": "Albany", "zip": "12208"},
    {"name": "Brownies", "address": "1686 Central Ave", "city": "Albany", "zip": "12205"},
    {"name": "Capital District Cannabis & Wellness Inc.", "address": "997 Central Ave Ste 200", "city": "Albany", "zip": "12205"},
    {"name": "Cannabicity Albany", "address": "489 Delaware Ave", "city": "Albany", "zip": "12209"},
    {"name": "Dark Horse", "address": "15 Centre St", "city": "Albany", "zip": "12207"},
    {"name": "EMERALDZ INC.", "address": "272 Delaware Ave", "city": "Albany", "zip": "12209"},
    {"name": "Silver Cannabis Company", "address": "10 Executive Park Dr", "city": "Albany", "zip": "12203"},
    {"name": "Genesis Cannabis, LLC", "address": "300 Broadway", "city": "Albany", "zip": "12207"},
    {"name": "Hold Up Roll Up, LLC", "address": "196 Washington Ave", "city": "Albany", "zip": "12210"},
    {"name": "Mr Good Vybz", "address": "25 N Pearl St", "city": "Albany", "zip": "12207"},
    {"name": "Robinson's Dispensary", "address": "106 Everett Rd", "city": "Albany", "zip": "12205"},
    {"name": "Stay Blessed LLC", "address": "1284 Central Ave", "city": "Albany", "zip": "12205"},
    {"name": "Capital Cannabis", "address": "2028 Western Ave", "city": "Albany", "zip": "12203"},
    {"name": "Southern Tier Cannabis Inc.", "address": "30 N Main St", "city": "Alfred", "zip": "14802"},
    {"name": "Buffalo Rush Fam Future, LLC", "address": "2521 Niagara Falls Blvd", "city": "Amherst", "zip": "14228"},
    {"name": "Green Leaf Holdings group llc", "address": "2121 Niagarafall Blvd", "city": "Amherst", "zip": "14215"},
    {"name": "Green Spectrum Sampling LLC", "address": "1101 Niagara Falls Blvd", "city": "Amherst", "zip": "14226"},
    {"name": "Herbalwai LLC", "address": "6970 Transit Rd", "city": "Amherst", "zip": "14221"},
    {"name": "Leaf Plug", "address": "3341 Sheridan Dr", "city": "Amherst", "zip": "14226"},
    {"name": "Tree Head Culture", "address": "665 N French Rd", "city": "Amherst", "zip": "14228"},
    {"name": "AMSTERDAM CANNABIS, INC.", "address": "1451 State Highway 5S", "city": "Amsterdam", "zip": "12010"},
    {"name": "Village one stop smoke shop inc.", "address": "11 Commercial St", "city": "Angola", "zip": "14006"},
    {"name": "Seaweed RBNY", "address": "7313 Beach Channel Dr", "city": "Arverne", "zip": "11692"},
    {"name": "Astoria Bud Boutique", "address": "3012 Astoria Blvd", "city": "Astoria", "zip": "11102"},
    {"name": "Cannavita", "address": "30-30 Steinway St", "city": "Astoria", "zip": "11103"},
    {"name": "HIGH CITY CANNABIS LLC", "address": "2235 31st St", "city": "Astoria", "zip": "11105"},
    {"name": "Terp Bros", "address": "3610 Ditmars Blvd", "city": "Astoria", "zip": "11105"},
    {"name": "Luminare LLC", "address": "2906 34th Ave", "city": "Astoria", "zip": "11106"},
    {"name": "Potluck Project LLC", "address": "1114 Main Ave", "city": "Astoria", "zip": "11102"},
    {"name": "Urban Weeds LLC", "address": "31-35 Steinway St", "city": "Astoria", "zip": "11103"},
    {"name": "Asking Edward, LLC", "address": "48 E Genesee St", "city": "Auburn", "zip": "13021"},
    {"name": "Lake Goat LLC", "address": "41-43 Genesee St", "city": "Auburn", "zip": "13021"},
    {"name": "The Dispensary of CNY, Inc.", "address": "96 Grant Ave", "city": "Auburn", "zip": "13021"},
    {"name": "BY ANY OTHER NAME", "address": "946 FULTON STREET", "city": "BROOKLYN", "zip": "11238"},
    {"name": "Stratus Dispensary", "address": "1258 Deer Park Ave", "city": "Babylon", "zip": "11703"},
    {"name": "Lucky Dog 420", "address": "974 State Route 67", "city": "Ballston Spa", "zip": "12020"},
    {"name": "Island Vibes Cannabis Dispensary", "address": "201 Northline Rd", "city": "Ballston Spa", "zip": "12020"},
    {"name": "Leaf & Fog", "address": "2124 Doubleday Ave # 2", "city": "Ballston Spa", "zip": "12020"},
    {"name": "Mrs Green's CANNAry", "address": "204 E Main St", "city": "Batavia", "zip": "14020"},
    {"name": "Crystonio, LLC", "address": "230 W Main St", "city": "Batavia", "zip": "14020"},
    {"name": "Aroma Farms Inc", "address": "20917 Northern Blvd", "city": "Bayside", "zip": "11361"},
    {"name": "Canna Buddha Corp", "address": "21546 39th Ave", "city": "Bayside", "zip": "11361"},
    {"name": "NY ELITE CANNABIS", "address": "4215 Bell Blvd", "city": "Bayside", "zip": "11361"},
    {"name": "Weed Mart By New Metro", "address": "22150 Horace Harding Expy", "city": "Bayside", "zip": "11364"},
    {"name": "The Station", "address": "463 Main St", "city": "Beacon", "zip": "12508"},
    {"name": "M & M Neighborhood Convenience Inc.", "address": "246-01 Jamaica Ave", "city": "Bellerose", "zip": "11426"},
    {"name": "NYCCE", "address": "24809 Jericho Tpke", "city": "Bellerose", "zip": "11426"},
    {"name": "PSUW LLC", "address": "28 Sawgrass Dr", "city": "Bellport", "zip": "11713"},
    {"name": "Blissful Buds", "address": "1332 Upper Front St Ste 4", "city": "Binghamton", "zip": "13901"},
    {"name": "Just Breathe", "address": "75 Court St", "city": "Binghamton", "zip": "13901"},
    {"name": "Flynnstoned Cannabis Company", "address": "1143 Upper Front St", "city": "Binghamton", "zip": "13905"},
    {"name": "Solo Greenery", "address": "439 Court St", "city": "Binghamton", "zip": "13904"},
    {"name": "Tranquil Arc, LLC", "address": "1167-1171 Vestal Ave", "city": "Binghamton", "zip": "13903"},
    {"name": "Vivid Wellness, LLC", "address": "242 Main St", "city": "Binghamton", "zip": "13905"},
    {"name": "Command Cannabis Dispensary Inc.", "address": "3871 S Park Ave", "city": "Blasdell", "zip": "14219"},
    {"name": "Just a Little Higher Briarwood", "address": "138-72 Queens Blvd", "city": "Briarwood", "zip": "11435"},
    {"name": "Budhampton LLC", "address": "2033 Montauk Hwy", "city": "Bridgehampton", "zip": "11932"},
    {"name": "Evergreen Retail", "address": "51 N. Main St", "city": "Brockport", "zip": "14420"},
    {"name": "Exotic Farms LLC", "address": "203 Main St", "city": "Brockport", "zip": "14420"},
    {"name": "Bleu Leaf Dispensary Inc.", "address": "2034 Jerome Ave", "city": "Bronx", "zip": "10453"},
    {"name": "CANNABIS HORIZON HOLDINGS", "address": "938 Intervale Ave", "city": "Bronx", "zip": "10459"},
    {"name": "Hush", "address": "2460 Williamsbridge Rd Fl 1", "city": "Bronx", "zip": "10469"},
    {"name": "Freshly Baked NYC", "address": "2375 Arthur Ave", "city": "Bronx", "zip": "10458"},
    {"name": "Say Less", "address": "3764 E Tremont Ave", "city": "Bronx", "zip": "10465"},
    {"name": "Frass Box Cannabis LLC", "address": "3633 Kingsbridge Ave", "city": "Bronx", "zip": "10463"},
    {"name": "GUARDIAN WELLNESS LLC", "address": "2500 Arthur Ave", "city": "Bronx", "zip": "10458"},
    {"name": "Garden Bliss LLC", "address": "1031 Southern Blvd", "city": "Bronx", "zip": "10459"},
    {"name": "Hibernica", "address": "3220 Westchester Ave", "city": "Bronx", "zip": "10461"},
    {"name": "SESH NYC", "address": "4219 Webster Ave", "city": "Bronx", "zip": "10470"},
    {"name": "I Bud You NY, Inc", "address": "898 Gerard Ave", "city": "Bronx", "zip": "10452"},
    {"name": "J&J Merch Inc.", "address": "516 Timpson Pl", "city": "Bronx", "zip": "10455"},
    {"name": "LITBIS II LLC", "address": "3535 White Plains Rd", "city": "Bronx", "zip": "10467"},
    {"name": "BRONX JOINT", "address": "925 Hunts Point Ave", "city": "Bronx", "zip": "10459"},
    {"name": "My Bud 420 Inc.", "address": "1798 E Tremont Ave", "city": "Bronx", "zip": "10460"},
    {"name": "NY Retail 2 Inc.", "address": "372 E Fordham Rd", "city": "Bronx", "zip": "10458"},
    {"name": "Nube NYC LLC", "address": "3551 Boston Rd", "city": "Bronx", "zip": "10469"},
    {"name": "Celestial Herbs", "address": "3430 Boston rd", "city": "Bronx", "zip": "10467"},
    {"name": "Smartloop 3395 LLC", "address": "4101 Boston Rd", "city": "Bronx", "zip": "10466"},
    {"name": "Smoking Scholars LLC", "address": "784 Allerton Ave", "city": "Bronx", "zip": "10467"},
    {"name": "BX Buddiez", "address": "2935 3rd Ave", "city": "Bronx", "zip": "10455"},
    {"name": "Conbud", "address": "2412 3rd Ave", "city": "Bronx", "zip": "10454"},
    {"name": "Thurston Hall Partners LLC", "address": "2438 Grand Concourse", "city": "Bronx", "zip": "10458"},
    {"name": "Two Buds Dispensary", "address": "696 East 241st St", "city": "Bronx", "zip": "10470"},
    {"name": "Victory Dispensary LLC", "address": "3653 E Tremont Ave", "city": "Bronx", "zip": "10465"},
    {"name": "Weed Land Inc.", "address": "1260 Castle Hill Ave", "city": "Bronx", "zip": "10462"},
    {"name": "7 Leaf Clover", "address": "132 Metropolitan Ave", "city": "Brooklyn", "zip": "11249"},
    {"name": "HERBOLOGY", "address": "304 Ellery St", "city": "Brooklyn", "zip": "11206"},
    {"name": "Stashmaster", "address": "1119 Broadway", "city": "Brooklyn", "zip": "11221"},
    {"name": "4081 Companies, LLC", "address": "772 Nostrand Ave", "city": "Brooklyn", "zip": "11216"},
    {"name": "4081 Companies, LLC", "address": "378 Tompkins Ave", "city": "Brooklyn", "zip": "11216"},
    {"name": "58 GP AVENUE LLC", "address": "58 Greenpoint Ave", "city": "Brooklyn", "zip": "11222"},
    {"name": "Forever 4 20", "address": "1118 Pennsylvania Ave.", "city": "Brooklyn", "zip": "11207"},
    {"name": "Brooklyn Urban", "address": "148 Kingsland Ave", "city": "Brooklyn", "zip": "11222"},
    {"name": "ARE WE GOOD ENTERPRISES INC.", "address": "154 Vanderbilt Ave", "city": "Brooklyn", "zip": "11205"},
    {"name": "AT THE FACTORY", "address": "424 Troutman St", "city": "Brooklyn", "zip": "11237"},
    {"name": "Altitude NY LLC", "address": "807 Manhattan Avenue", "city": "Brooklyn", "zip": "11222"},
    {"name": "Animo CBD LLC", "address": "2180 Clarendon Rd", "city": "Brooklyn", "zip": "11226"},
    {"name": "Astro Management, Inc.", "address": "292 Atlantic Ave", "city": "Brooklyn", "zip": "11201"},
    {"name": "BK Exotic", "address": "1056 Flatbush Ave", "city": "Brooklyn", "zip": "11226"},
    {"name": "BK Greenery LLC", "address": "367 Flatbush Ave", "city": "Brooklyn", "zip": "11238"},
    {"name": "Flower Daddy", "address": "539 Metropolitan Ave", "city": "Brooklyn", "zip": "11211"},
    {"name": "Brooklyn Bourne Dispensary", "address": "2225 Church Avenue", "city": "Brooklyn", "zip": "11226"},
    {"name": "Flynnstoned Cannabis Company", "address": "8112 5th Ave", "city": "Brooklyn", "zip": "11209"},
    {"name": "Brooklyn Botanix LLC", "address": "61 Kent Ave", "city": "Brooklyn", "zip": "11249"},
    {"name": "Brooklyn Organic Buds LLC", "address": "623 Bergen St", "city": "Brooklyn", "zip": "11238"},
    {"name": "Bud City Cannabis LLC", "address": "3343 Fulton St", "city": "Brooklyn", "zip": "11208"},
    {"name": "Budega NYC", "address": "321 4th Ave", "city": "Brooklyn", "zip": "11215"},
    {"name": "Buzzy NY, LLC", "address": "137 Court St", "city": "Brooklyn", "zip": "11201"},
    {"name": "Misha's Flower Shop", "address": "299 Knickerbocker Ave", "city": "Brooklyn", "zip": "11237"},
    {"name": "CBJ Retail LLC", "address": "1019 Surf Ave", "city": "Brooklyn", "zip": "11224"},
    {"name": "Caffiend LLC", "address": "892 Wyckoff Ave", "city": "Brooklyn", "zip": "11237"},
    {"name": "HII", "address": "152 Bedford Ave", "city": "Brooklyn", "zip": "11249"},
    {"name": "Cannalicious LLC", "address": "435 5th Ave", "city": "Brooklyn", "zip": "11215"},
    {"name": "Case Management", "address": "3169 Coney Island Ave", "city": "Brooklyn", "zip": "11235"},
    {"name": "Chronic Brooklyn", "address": "483 3rd Ave", "city": "Brooklyn", "zip": "11215"},
    {"name": "Be.", "address": "204-206 Flatbush Ave", "city": "Brooklyn", "zip": "11217"},
    {"name": "SOULMATE", "address": "237 Dekalb Ave", "city": "Brooklyn", "zip": "11205"},
    {"name": "DIAMOND DISPENSARY LLC", "address": "455 Graham Ave", "city": "Brooklyn", "zip": "11222"},
    {"name": "DISCO HERBATORY LLC", "address": "692 Grand St", "city": "Brooklyn", "zip": "11211"},
    {"name": "DISPO/BK LLC", "address": "588 4th Ave", "city": "Brooklyn", "zip": "11215"},
    {"name": "DTPFF Enterprises LLC", "address": "69 Graham Ave", "city": "Brooklyn", "zip": "11206"},
    {"name": "DTV Enterprises", "address": "314 Livingston St", "city": "Brooklyn", "zip": "11217"},
    {"name": "Dizzpensary LLC", "address": "227 Smith St", "city": "Brooklyn", "zip": "11231"},
    {"name": "ELEVATED", "address": "302 Kings Hwy", "city": "Brooklyn", "zip": "11223"},
    {"name": "ERUDITO CANNABIS BOUTIQUE", "address": "120 Union St", "city": "Brooklyn", "zip": "11231"},
    {"name": "Sunflower Dispensary", "address": "377 Metropolitan Ave", "city": "Brooklyn", "zip": "11211"},
    {"name": "Euphoria Dispensary of New York, LLC", "address": "1582 Pitkin Ave", "city": "Brooklyn", "zip": "11212"},
    {"name": "Exotic Herbals LLC", "address": "428 Rogers Ave", "city": "Brooklyn", "zip": "11225"},
    {"name": "Fireleaf, LLC", "address": "2102 Ralph Ave", "city": "Brooklyn", "zip": "11234"},
    {"name": "Mommy's Bodega", "address": "150 Atlantic Ave", "city": "Brooklyn", "zip": "11201"},
    {"name": "OC DISPENSARY", "address": "769 Franklin Ave", "city": "Brooklyn", "zip": "11238"},
    {"name": "The Brooklyn Dispensary", "address": "2129 Flatbush Ave", "city": "Brooklyn", "zip": "11234"},
    {"name": "Friends NYC", "address": "56 Bogart St", "city": "Brooklyn", "zip": "11206"},
    {"name": "The Travel Agency Downtown Brooklyn", "address": "118 Flatbush Ave", "city": "Brooklyn", "zip": "11217"},
    {"name": "Green Apple Distribution Ltd.", "address": "572 Manhattan Ave", "city": "Brooklyn", "zip": "11222"},
    {"name": "Green Heights", "address": "19 Green Ave", "city": "Brooklyn", "zip": "11238"},
    {"name": "Greenerie LLC", "address": "301 Clifton Pl", "city": "Brooklyn", "zip": "11216"},
    {"name": "Grow Together", "address": "2370 Coney Island Ave", "city": "Brooklyn", "zip": "11223"},
    {"name": "HIGHSENTIAL LLC", "address": "301 Brighton Beach Ave", "city": "Brooklyn", "zip": "11235"},
    {"name": "HUDSON ECONOMICS LLC", "address": "1981 86th St", "city": "Brooklyn", "zip": "11214"},
    {"name": "Hand in Bush LLC", "address": "834 Dekalb Ave", "city": "Brooklyn", "zip": "11221"},
    {"name": "HAPPY BUDS BROOKLYN", "address": "225 Malcolm X Blvd", "city": "Brooklyn", "zip": "11221"},
    {"name": "High Love LLC", "address": "1165 Bedford Ave", "city": "Brooklyn", "zip": "11216"},
    {"name": "High of Brooklyn LLC", "address": "64 Henry St", "city": "Brooklyn", "zip": "11201"},
    {"name": "HUDSON HAZeLLC", "address": "3043 Fulton St", "city": "Brooklyn", "zip": "11208"},
    {"name": "Gotham Williamsburg", "address": "300 Kent Avenue", "city": "Brooklyn", "zip": "11249"},
    {"name": "Lease From Me", "address": "2668 Coney Island Ave", "city": "Brooklyn", "zip": "11223"},
    {"name": "JWA DH Inc", "address": "360 7th Ave", "city": "Brooklyn", "zip": "11215"},
    {"name": "Jojo Show LLC", "address": "1584 Flatbush Ave", "city": "Brooklyn", "zip": "11210"},
    {"name": "Jungle Kingdom Flower Company LLC", "address": "515 Nostrand Ave", "city": "Brooklyn", "zip": "11216"},
    {"name": "KBAT ENTERPRISES INC.", "address": "1077 Atlantic Ave", "city": "Brooklyn", "zip": "11238"},
    {"name": "Kushmart", "address": "1413 Kings Hwy", "city": "Brooklyn", "zip": "11229"},
    {"name": "Kushwickz, Inc.", "address": "595 Bushwick Ave", "city": "Brooklyn", "zip": "11206"},
    {"name": "LIT NYC INC", "address": "456 Avenue P", "city": "Brooklyn", "zip": "11223"},
    {"name": "High Dankery", "address": "7815 3rd Ave", "city": "Brooklyn", "zip": "11209"},
    {"name": "MZDZ Corp", "address": "875 Neptune Ave", "city": "Brooklyn", "zip": "11224"},
    {"name": "NSH LLC", "address": "2280 Flatbush Ave", "city": "Brooklyn", "zip": "11234"},
    {"name": "Society House", "address": "2441 Flatbush Ave", "city": "Brooklyn", "zip": "11234"},
    {"name": "LINDEN TREE", "address": "2552 Linden Blvd", "city": "Brooklyn", "zip": "11208"},
    {"name": "OET INC.", "address": "733 Flatbush Ave", "city": "Brooklyn", "zip": "11226"},
    {"name": "ONE STOP DELI & CANDY STORE INC", "address": "9 Newkirk Plz", "city": "Brooklyn", "zip": "11226"},
    {"name": "OTEC", "address": "1155 Liberty Ave", "city": "Brooklyn", "zip": "11208"},
    {"name": "PRIME TIME CANNABIS", "address": "856 KNICKERBOCKER AVENUE", "city": "Brooklyn", "zip": "11207"},
    {"name": "Paradise Cannabis LLC", "address": "1557 Fulton St", "city": "Brooklyn", "zip": "11216"},
    {"name": "Puro vita enterprises inc.", "address": "288 flushing Ave", "city": "Brooklyn", "zip": "11205"},
    {"name": "Quality Roots, LLC", "address": "330 Tompkins Ave", "city": "Brooklyn", "zip": "11216"},
    {"name": "R & R Remedies", "address": "287 Harrison Pl", "city": "Brooklyn", "zip": "11237"},
    {"name": "Kaya Bliss Dispensary", "address": "8412 3rd Ave", "city": "Brooklyn", "zip": "11209"},
    {"name": "Ramon Reyes LLC", "address": "453 Fulton St", "city": "Brooklyn", "zip": "11201"},
    {"name": "Rockaway Moonshot, LLC", "address": "3405 Avenue H", "city": "Brooklyn", "zip": "11210"},
    {"name": "SUPPLY DESIGN LLC", "address": "2201 Avenue U", "city": "Brooklyn", "zip": "11229"},
    {"name": "Salt City Naturals, LLC", "address": "61 N 11th St", "city": "Brooklyn", "zip": "11249"},
    {"name": "The Emerald Dispensary", "address": "85 Suydam St", "city": "Brooklyn", "zip": "11221"},
    {"name": "TIMES SQUARE SHOP INC", "address": "1702 Sheepshead Bay Rd", "city": "Brooklyn", "zip": "11235"},
    {"name": "Take N Toke Herbal Healing Solutions Inc", "address": "994 Atlantic Ave", "city": "Brooklyn", "zip": "11238"},
    {"name": "Sunset Cannabis Club", "address": "512 55th St", "city": "Brooklyn", "zip": "11220"},
    {"name": "The Hibrary 695 Inc", "address": "695 5th Ave", "city": "Brooklyn", "zip": "11215"},
    {"name": "The Sophisticated Stoner", "address": "1601 Avenue U", "city": "Brooklyn", "zip": "11229"},
    {"name": "Tiki Leaves LLC", "address": "1511 Neptune Avenue", "city": "Brooklyn", "zip": "11224"},
    {"name": "Twisted Vibration LLC", "address": "301 Broadway", "city": "Brooklyn", "zip": "11211"},
    {"name": "Upstate Edge, LLC", "address": "387 Van Brunt St.", "city": "Brooklyn", "zip": "11231"},
    {"name": "Washington Place Dispensary LLC", "address": "2 Jewel St", "city": "Brooklyn", "zip": "11222"},
    {"name": "Matawana", "address": "533 5th ave", "city": "Brooklyn", "zip": "11215"},
    {"name": "Womens United Alliance LLC", "address": "1370 Ralph Ave", "city": "Brooklyn", "zip": "11236"},
    {"name": "Greene street cannabis co.", "address": "3448 Nostrand Ave", "city": "Brooklyn", "zip": "11229"},
    {"name": "Yurplegreene Holdings NY LLC", "address": "195 Morgan Ave", "city": "Brooklyn", "zip": "11237"},
    {"name": "bzd enterprises llc", "address": "1102 Bedford Ave", "city": "Brooklyn", "zip": "11216"},
    {"name": "3 Guys Canna, LLC", "address": "145 Ganson St", "city": "Buffalo", "zip": "14203"},
    {"name": "Buffalo Cannabis Outlet", "address": "3807 Harlem Rd", "city": "Buffalo", "zip": "14215"},
    {"name": "82-J LLC", "address": "1673 Hertle Avenue", "city": "Buffalo", "zip": "14216"},
    {"name": "Astrid Holdings LLC", "address": "758 Elmwood Ave", "city": "Buffalo", "zip": "14222"},
    {"name": "Best Budz Cannabis Co. LLC", "address": "146 Virginia St", "city": "Buffalo", "zip": "14201"},
    {"name": "Buffalo Cannabis Connect, LLC", "address": "904 Elmwood Ave", "city": "Buffalo", "zip": "14222"},
    {"name": "Ether", "address": "5100 Genesee St", "city": "Buffalo", "zip": "14225"},
    {"name": "Cannaspace Inc.", "address": "4151 McKinley Pkwy", "city": "Buffalo", "zip": "14219"},
    {"name": "MARY JANES- A LEGACY 2 LEGAL DISPENSARY", "address": "2179 Sheridan Dr Tonawanda NY14223", "city": "Buffalo", "zip": "14223"},
    {"name": "Dank716 LLC (new EIN 92-3339286)", "address": "501 Main St", "city": "Buffalo", "zip": "14203"},
    {"name": "Canterra", "address": "451 Elmwood Ave Ste 105", "city": "Buffalo", "zip": "14222"},
    {"name": "Erie County Cannabis LLC", "address": "1727 Genesee St", "city": "Buffalo", "zip": "14211"},
    {"name": "WeedNDeed", "address": "900 Niagara Falls Blvd", "city": "Buffalo", "zip": "14223"},
    {"name": "Fortwentie inc.", "address": "187 Delaware Ave", "city": "Buffalo", "zip": "14202"},
    {"name": "Gtb2 Enterprise Llc", "address": "3118 Main St", "city": "Buffalo", "zip": "14214"},
    {"name": "Mammoth Cannabis", "address": "212 Ohio St", "city": "Buffalo", "zip": "14204"},
    {"name": "Star Buds", "address": "396 Kenmore Ave", "city": "Buffalo", "zip": "14223"},
    {"name": "Premier Earth corp.", "address": "1297 Hertel Ave", "city": "Buffalo", "zip": "14216"},
    {"name": "RKWS, LLC", "address": "577 Forest Ave", "city": "Buffalo", "zip": "14222"},
    {"name": "Secret Garden 716", "address": "1363 Delaware Ave", "city": "Buffalo", "zip": "14209"},
    {"name": "The BonTemps Firm Retail, LLC", "address": "232 Allen St", "city": "Buffalo", "zip": "14201"},
    {"name": "The Cannabis Vault LLC", "address": "2234 Seneca St", "city": "Buffalo", "zip": "14210"},
    {"name": "The Greener Mile", "address": "1923 Seneca St", "city": "Buffalo", "zip": "14210"},
    {"name": "WNY Greenhouse LLC", "address": "2675 Main St", "city": "Buffalo", "zip": "14214"},
    {"name": "The Cannabis Store", "address": "1936 S Park Ave", "city": "Buffalo", "zip": "14220"},
    {"name": "Beleaf Calverton", "address": "4462 Middle Country Rd", "city": "Calverton", "zip": "11933"},
    {"name": "Good Life Collective Fingerlakes", "address": "230 S Main St", "city": "Canandaigua", "zip": "14424"},
    {"name": "NextGen Endeavors, LLC", "address": "51 Main St", "city": "Canton", "zip": "13617"},
    {"name": "Black River Supply Company, LLC", "address": "15 Bridge Street", "city": "Carthage", "zip": "13619"},
    {"name": "WILDE ROOTS DISPENSARY", "address": "4179 State Route 20", "city": "Castleton", "zip": "12033"},
    {"name": "Catskill Cannabis NY LLC", "address": "170 W Bridge St", "city": "Catskill", "zip": "12414"},
    {"name": "The Canna Guy LLC", "address": "411 US-11", "city": "Central Square", "zip": "13036"},
    {"name": "AMSM LLC", "address": "2442 Clinton Street", "city": "Cheektowaga", "zip": "14224"},
    {"name": "Buffalo Cannabis Store LLC", "address": "2760 Union Rd", "city": "Cheektowaga", "zip": "14227"},
    {"name": "Cloud 9 Dispensary, LLC", "address": "1380 French Rd., Suite # 1", "city": "Cheektowaga", "zip": "14043"},
    {"name": "King of Budz", "address": "2200 Walden Ave", "city": "Cheektowaga", "zip": "14225"},
    {"name": "Gentleman's Hemp L.L.C.", "address": "14 RT 9H", "city": "Claverack", "zip": "12513"},
    {"name": "Raven's Joint", "address": "4106 State Route 31 Ste 903", "city": "Clay", "zip": "13041"},
    {"name": "Rise", "address": "1675 US-9", "city": "Clifton Park", "zip": "12065"},
    {"name": "THE HIGHEST PEAK LLC", "address": "1508 US-9", "city": "Clifton Park", "zip": "12065"},
    {"name": "The Bakery", "address": "1099 New Loudon Rd", "city": "Cohoes", "zip": "12047"},
    {"name": "CB BudCo LLC", "address": "243 Wolf Rd", "city": "Colonie", "zip": "12205"},
    {"name": "Legacy Dispensary", "address": "1839 Central Ave", "city": "Colonie", "zip": "12205"},
    {"name": "Mister Greens", "address": "81 Wolf Rd", "city": "Colonie", "zip": "12205"},
    {"name": "Green Leaf Wellness Co. LLC", "address": "971 Albany Shaker Road", "city": "Colonie", "zip": "12110"},
    {"name": "The HighEnd Dispensary", "address": "1410 Central Ave", "city": "Colonie", "zip": "12205"},
    {"name": "Peace of Woodstock", "address": "406 Middle Country Rd", "city": "Coram", "zip": "11727"},
    {"name": "Culture Cannabis Company", "address": "90 E Market St Unit 101", "city": "Corning", "zip": "14830"},
    {"name": "Union Chill Cannabis NY LLC", "address": "34 W Pulteney St", "city": "Corning", "zip": "14830"},
    {"name": "MamitaJoy LLC", "address": "5520 103rd St", "city": "Corona", "zip": "11368"},
    {"name": "LakeHouse Cannabis, LLC", "address": "156 Clinton Ave", "city": "Cortland", "zip": "13045"},
    {"name": "Kings House of Fire", "address": "3006 E Main St", "city": "Cortlandt Manor", "zip": "10567"},
    {"name": "Harvest Hills", "address": "1817 State Route 23", "city": "Craryville", "zip": "12521"},
    {"name": "Dansville Dispensary Corporation", "address": "9483 Foster Wheeler Rd", "city": "Dansville", "zip": "14437"},
    {"name": "Big Jule's Dispensary Inc.", "address": "1070 Long Island Ave", "city": "Deer Park", "zip": "11729"},
    {"name": "Long Island Cannabis Club", "address": "94 East Industry Court", "city": "Deer Park", "zip": "11729"},
    {"name": "DDRJ Holdings LLC", "address": "880 Grand Blvd", "city": "Deer Park", "zip": "11729"},
    {"name": "Legendary Bliss, LLC", "address": "9 Connor Ln", "city": "Deer Park", "zip": "11729"},
    {"name": "Catskill Botanicals", "address": "53 Main St.", "city": "Delhi", "zip": "13753"},
    {"name": "2601 Genesee LLC", "address": "3478 Walden Ave", "city": "Depew", "zip": "14043"},
    {"name": "Dream Daze LLC", "address": "5100 Transit Rd", "city": "Depew", "zip": "14043"},
    {"name": "Herbal I.Q.", "address": "6300 Transit Rd", "city": "Depew", "zip": "14043"},
    {"name": "THE PHINEST BUDS LLC", "address": "576 Dick Rd, Suite 10A", "city": "Depew", "zip": "14043"},
    {"name": "The Smoking Buffalo LLC", "address": "2540 George Urban Blvd", "city": "Depew", "zip": "14043"},
    {"name": "DDMM Dispensary LLC", "address": "146 Front St", "city": "Deposit", "zip": "13754"},
    {"name": "Dryden Dispensary", "address": "2207 Dryden Rd", "city": "Dryden", "zip": "13053"},
    {"name": "Happy Times Cannabis Co.", "address": "9170 Transit Rd", "city": "East Amherst", "zip": "14051"},
    {"name": "Zenith Grove, LLC", "address": "9450 Transit Rd", "city": "East Amherst", "zip": "14051"},
    {"name": "East Leaf Dispensary", "address": "203 Main St", "city": "East Aurora", "zip": "14052"},
    {"name": "ENFLOR LLC", "address": "3264 85th St", "city": "East Elmhurst", "zip": "11370"},
    {"name": "Smokey Paradise LLC", "address": "574 Columbia Tpke", "city": "East Greenbush", "zip": "12061"},
    {"name": "Sessco Corp.", "address": "115 Main St", "city": "East Rochester", "zip": "14445"},
    {"name": "Strong Strains", "address": "19 Technology Dr", "city": "East Setauket", "zip": "11733"},
    {"name": "Rise", "address": "6701 Manlius Center Road", "city": "East Syracuse", "zip": "13057"},
    {"name": "Verilife", "address": "5841 Bridge Street", "city": "East Syracuse", "zip": "13057"},
    {"name": "Ellenville Cannabis LLC", "address": "37 N Main St", "city": "Ellenville", "zip": "12428"},
    {"name": "CEBEDE, LLC", "address": "24 Washington St", "city": "Ellicottville", "zip": "14731"},
    {"name": "The Goodie Bag, LLC", "address": "260 Clemens Center Pkwy", "city": "Elmira", "zip": "14901"},
    {"name": "Three Buds", "address": "80 N Main St", "city": "Fairport", "zip": "14450"},
    {"name": "PLANET NUGG", "address": "2043 Wellwood Ave", "city": "Farmingdale", "zip": "11735"},
    {"name": "DUTCHMEN OF CENTRAL LLC", "address": "79 Gazza Blvd", "city": "Farmingdale", "zip": "11735"},
    {"name": "Empire Plant Services Holdings LLC", "address": "900 Broadhollow Road", "city": "Farmingdale", "zip": "11735"},
    {"name": "Happy Days Dispensary Inc.", "address": "105 Route 109", "city": "Farmingdale", "zip": "11735"},
    {"name": "JDR CANN LLC", "address": "67 Milbar Blvd", "city": "Farmingdale", "zip": "11735"},
    {"name": "The Botanist", "address": "2365 Broadhollow Rd.", "city": "Farmingdale", "zip": "11737"},
    {"name": "Big Apple Bud Co.", "address": "228 Route 109", "city": "Farmingdale", "zip": "11735"},
    {"name": "Small Leaf 79 LLC", "address": "2400 N Ocean Ave", "city": "Farmingville", "zip": "11738"},
    {"name": "Organic Blooms LLC", "address": "2971 Route 426", "city": "Findley Lake", "zip": "14736"},
    {"name": "Fishkill Cannabis", "address": "814 Route 52", "city": "Fishkill", "zip": "12524"},
    {"name": "Kornegay & Son LLC", "address": "982 Main St Ste 5", "city": "Fishkill", "zip": "12524"},
    {"name": "Potency", "address": "18 Westage Dr Ste 7", "city": "Fishkill", "zip": "12524"},
    {"name": "10613 Northern LLC", "address": "136-15 Roosevelt Ave", "city": "Flushing", "zip": "11354"},
    {"name": "Golden Buds", "address": "5906 Myrtle Ave", "city": "Flushing", "zip": "11385"},
    {"name": "BEAST COAST GROUP LLC", "address": "16105 29th Ave STORE", "city": "Flushing", "zip": "11358"},
    {"name": "Just a Little Higher Kew Gardens", "address": "14601 Union Tpke", "city": "Flushing", "zip": "11367"},
    {"name": "JACKPOT 420 LLC", "address": "133-36 WHITESTONE EXPRESSWAY", "city": "Flushing", "zip": "11354"},
    {"name": "MAGIC TREE CANNABIS COMPANY CORPORATION", "address": "16806 Union Tpke", "city": "Flushing", "zip": "11366"},
    {"name": "Mirae Corp", "address": "40-28 Murray Street", "city": "Flushing", "zip": "11354"},
    {"name": "Pramukh 162", "address": "16220 Northern Blvd", "city": "Flushing", "zip": "11358"},
    {"name": "Curaleaf NY, LLC", "address": "107-18 70th Rd.", "city": "Forest Hills", "zip": "11375"},
    {"name": "LAR MEMORABILIA LLC", "address": "6354 108th St", "city": "Forest Hills", "zip": "11375"},
    {"name": "Soho Dispensary", "address": "10729A 71st Ave", "city": "Forest Hills", "zip": "11375"},
    {"name": "Comfort Care Services inc.", "address": "99-00 Metropolitan Avenue", "city": "Forest Hills New York", "zip": "11375"},
    {"name": "High Road", "address": "185-24 Horace Harding Expressway", "city": "Fresh Meadows", "zip": "11365"},
    {"name": "Leafy Wonders", "address": "956 S 1st St", "city": "Fulton", "zip": "13069"},
    {"name": "GREEN FLOWER WELLNESS 5 LLC", "address": "270-01 HILLSIDE AVE", "city": "GLEN OAKS", "zip": "11004"},
    {"name": "High Points Dispensary", "address": "811 Canandaigua Rd", "city": "Geneva", "zip": "14456"},
    {"name": "Twisted Cannabis FLX", "address": "501 Exchange St", "city": "Geneva", "zip": "14456"},
    {"name": "GREEN FLOWER WELLNESS 6 LLC", "address": "25818 Hillside Ave", "city": "Glen Oaks", "zip": "11004"},
    {"name": "GSS Consulting LLC", "address": "29-27 41st Avenue", "city": "Glen Oaks", "zip": "11004"},
    {"name": "R&R CANNABIS LLC", "address": "12 Hudson Ave", "city": "Glens Falls", "zip": "12801"},
    {"name": "Windy Hill Wellness", "address": "130 Broad St Ste 7 & 8", "city": "Glens Falls", "zip": "12801"},
    {"name": "Reef", "address": "2532 Route 9N", "city": "Greenfield Center", "zip": "12833"},
    {"name": "Green Witch Dispensary LLC", "address": "1156 Route 29", "city": "Greenwich", "zip": "12834"},
    {"name": "Windy Hill Wellness", "address": "106 Main St", "city": "Greenwich", "zip": "12834"},
    {"name": "Cannabis Central", "address": "1520 Crescent Rd", "city": "Halfmoon", "zip": "12065"},
    {"name": "Evexia Cannabis", "address": "217 Guideboard Rd", "city": "Halfmoon", "zip": "12065"},
    {"name": "716 Cannabis", "address": "5161 Camp Rd", "city": "Hamburg", "zip": "14075"},
    {"name": "The Hippie Cannabis Co", "address": "4433 Southwestern Blvd", "city": "Hamburg", "zip": "14075"},
    {"name": "Brightway Services, Inc", "address": "18 Apex Rd", "city": "Hancock", "zip": "13783"},
    {"name": "The Highline", "address": "45 Main St", "city": "Hastings On Hudson", "zip": "10706"},
    {"name": "202 Cannabis Co.", "address": "81 W Ramapo Rd Unit 1", "city": "Haverstraw", "zip": "10923"},
    {"name": "Green Veteran NY LLC", "address": "35 Route 9W", "city": "Haverstraw", "zip": "10927"},
    {"name": "OKKERSNY LLC", "address": "147 Route 9W", "city": "Haverstraw", "zip": "10927"},
    {"name": "Mango Cannabis", "address": "3553 West Henrietta Road", "city": "Henrietta", "zip": "14623"},
    {"name": "Urban Pulse, LLC", "address": "3740 W Henrietta", "city": "Henrietta", "zip": "14623"},
    {"name": "7420 Utrecht LLC", "address": "316  East State St", "city": "Herkimer", "zip": "13350"},
    {"name": "BWell Holdings NY, Inc.", "address": "3565 US Highway 9W", "city": "Highland", "zip": "12528"},
    {"name": "Classy Canna, LLC", "address": "8 N Main St", "city": "Homer", "zip": "13077"},
    {"name": "MJ Dispensary", "address": "201 W Main St", "city": "Honeoye Falls", "zip": "14472"},
    {"name": "World Piece, LLC", "address": "3162 Lake Rd Ste 4", "city": "Horseheads", "zip": "14845"},
    {"name": "RAGTIME NEWSTAND AND LOTTO, INC.", "address": "15748 Crossbay Blvd", "city": "Howard Beach", "zip": "11414"},
    {"name": "Cannafamily Dispensary", "address": "102-15 159th Road", "city": "Howard Beach", "zip": "11414"},
    {"name": "Blaze NY LLC", "address": "517-519 Columbia St", "city": "Hudson", "zip": "12534"},
    {"name": "RIVERBEND DISPENSARY", "address": "531 Warren St", "city": "Hudson", "zip": "12534"},
    {"name": "Goldleaf Cannabis", "address": "235 Fairview Ave", "city": "Hudson", "zip": "12534"},
    {"name": "Gotham Hudson", "address": "260 Warren St", "city": "Hudson", "zip": "12534"},
    {"name": "Green Leaf Herbalists", "address": "167 Union Turnpike", "city": "Hudson", "zip": "12534"},
    {"name": "High Society Dispensary LLC", "address": "345 Main St Ste 2", "city": "Hudson Falls", "zip": "12839"},
    {"name": "The Highly Connected Dispensary", "address": "423 Franklin St", "city": "Ithaca", "zip": "14850"},
    {"name": "ATNC INC", "address": "105 Dryden Rd", "city": "Ithaca", "zip": "14850"},
    {"name": "Aspire", "address": "205 N Fulton St", "city": "Ithaca", "zip": "14850"},
    {"name": "Altitude Ithaca", "address": "1429 Danby Rd", "city": "Ithaca", "zip": "14850"},
    {"name": "Corner House, LLC", "address": "1708 Trumansburg Rd", "city": "Ithaca", "zip": "14850"},
    {"name": "WilliamJane", "address": "119 E State St", "city": "Ithaca", "zip": "14850"},
    {"name": "HIGH CLASS SMOKES INC.", "address": "8820 Roosevelt Ave", "city": "Jackson Heights", "zip": "11372"},
    {"name": "Purple Buds, Inc.", "address": "7520 Roosevelt Ave", "city": "Jackson Heights", "zip": "11372"},
    {"name": "Cali Happy Realty Corp", "address": "14310 Liberty Ave", "city": "Jamaica", "zip": "11435"},
    {"name": "Common Courtesy Dispensary Inc", "address": "13809 Jamaica Ave", "city": "Jamaica", "zip": "11435"},
    {"name": "Down To Earth Canna Inc", "address": "24815 Union Tpke", "city": "Jamaica", "zip": "11426"},
    {"name": "Good Grades LLC", "address": "16203 Jamaica Ave", "city": "Jamaica", "zip": "11432"},
    {"name": "JFK Cannabis Inc", "address": "17501 Rockaway Blvd", "city": "Jamaica", "zip": "11434"},
    {"name": "Silk Road NYC", "address": "16630 Jamaica Ave", "city": "Jamaica", "zip": "11432"},
    {"name": "Northern Lights Dispensary LLC", "address": "241-02 140th Ave.", "city": "Jamaica", "zip": "11422"},
    {"name": "Rosedale Cannabis Dispensary LLC", "address": "90-67 Sutphin Blvd.", "city": "Jamaica", "zip": "11435"},
    {"name": "WNRA LLC", "address": "13115 Merrick Blvd", "city": "Jamaica", "zip": "11434"},
    {"name": "Yeti Greenery", "address": "607 W 3rd St", "city": "Jamestown", "zip": "14701"},
    {"name": "Lifted", "address": "320 N Main St", "city": "Jamestown", "zip": "14701"},
    {"name": "Pike & Griff LLC", "address": "34 Scott St", "city": "Jamestown", "zip": "14701"},
    {"name": "Liquid Monkey", "address": "177 Fluvanna Ave", "city": "Jamestown", "zip": "14701"},
    {"name": "The Natural Dispensary", "address": "1067 E 2nd St", "city": "Jamestown", "zip": "14701"},
    {"name": "The Green House", "address": "4946 State Route 52 Unit 1", "city": "Jeffersonville", "zip": "12748"},
    {"name": "NY Cannabis Dispensary LLC", "address": "343 N Comrie Ave", "city": "Johnstown", "zip": "12095"},
    {"name": "Chesterfield Cannabis Co., LLC", "address": "89 Kent St", "city": "Keeseville", "zip": "12944"},
    {"name": "Nickel City Green, LLC", "address": "2981 Delaware Ave", "city": "Kenmore", "zip": "14217"},
    {"name": "the kokoro way, LLC", "address": "2454 Elmwood Ave", "city": "Kenmore", "zip": "14217"},
    {"name": "A & P DISPENSARY CORP", "address": "8137 Lefferts Blvd", "city": "Kew Gardens", "zip": "11415"},
    {"name": "A2B Luxury LLC", "address": "356 Broadway", "city": "Kingston", "zip": "12401"},
    {"name": "Fluent", "address": "445 State Route 28", "city": "Kingston", "zip": "12401"},
    {"name": "Kingston Cannabis LLC", "address": "728 Broadway", "city": "Kingston", "zip": "12401"},
    {"name": "Kingston NY Cannabis LLC", "address": "1221 Ulster Ave", "city": "Kingston", "zip": "12401"},
    {"name": "Lucky Green Ladies", "address": "365 S Wall St", "city": "Kingston", "zip": "12401"},
    {"name": "Catskill Mountain High", "address": "308 Plaza Rd", "city": "Kingston", "zip": "12401"},
    {"name": "Royal Blend Dispensary LLC", "address": "2223 State Route 32", "city": "Kingston", "zip": "12401"},
    {"name": "Sage Cannabis", "address": "268 Forest Hill Dr", "city": "Kingston", "zip": "12401"},
    {"name": "Liberty NY Cannabis, LLC", "address": "187 MILL ST", "city": "LIBERTY", "zip": "12754"},
    {"name": "Briar Hill Holdings LLC", "address": "1385 Abbott Rd", "city": "Lackawanna", "zip": "14218"},
    {"name": "Tree Market NY LLC", "address": "2470 Hamburg Tpke", "city": "Lackawanna", "zip": "14218"},
    {"name": "True North Cannabis LLC", "address": "1471 State Route 9", "city": "Lake George", "zip": "12845"},
    {"name": "The Mellow Moose", "address": "2192 Saranac Ave", "city": "Lake Placid", "zip": "12946"},
    {"name": "Smiley 370 LLC", "address": "370 Ronkonkoma Ave", "city": "Lake Ronkonkoma", "zip": "11779"},
    {"name": "High Tide", "address": "1829 Como Park Blvd", "city": "Lancaster", "zip": "14086"},
    {"name": "Notorious Tree NY LLC", "address": "5211 Broadway St Ste 300", "city": "Lancaster", "zip": "14086"},
    {"name": "The Greenery", "address": "683 New Loudon Rd", "city": "Latham", "zip": "12110"},
    {"name": "Verilife", "address": "2 Wade Road", "city": "Latham", "zip": "12110"},
    {"name": "State of Mind Dispensary, LLC", "address": "521 Troy Schenectady Rd", "city": "Latham", "zip": "12110"},
    {"name": "GOLD LEAF", "address": "1941 State Route 52", "city": "Liberty", "zip": "12754"},
    {"name": "The Chosen Pot", "address": "6669 West Main Road", "city": "Lima", "zip": "14485"},
    {"name": "JSE 26 Corp", "address": "24502 Horace Harding Expy", "city": "Little Neck", "zip": "11362"},
    {"name": "Queens Delight LLC", "address": "233-20 Northern Blvd", "city": "Little Neck", "zip": "11362"},
    {"name": "Good Daze Dispensary", "address": "25306 Northern Blvd", "city": "Little Neck", "zip": "11362"},
    {"name": "Venus Cannabis Shop, LLC", "address": "248-06 Northern Blvd", "city": "Little Neck", "zip": "11362"},
    {"name": "TJ'S CANNABIS CORP.", "address": "4205 Long Branch Rd Ste 5", "city": "Liverpool", "zip": "13090"},
    {"name": "Justin Germain", "address": "7570 OSWEGO ROAD", "city": "Liverpool", "zip": "13090"},
    {"name": "MANOR CANNA LLC", "address": "618 Old Route 17", "city": "Livingston Manor", "zip": "12758"},
    {"name": "3714 34th LLC", "address": "3714 34th St", "city": "Long Island City", "zip": "11101"},
    {"name": "BudBiz LLC", "address": "4445 Vernon Blvd", "city": "Long Island City", "zip": "11101"},
    {"name": "HF Dispensary LLC", "address": "28-31 Borden Avenue", "city": "Long Island City", "zip": "11101"},
    {"name": "Just a Little Higher LLC", "address": "2415 Queens Plz N Unit NR1", "city": "Long Island City", "zip": "11101"},
    {"name": "Nice Yield Stores", "address": "1050 Jackson Ave", "city": "Long Island City", "zip": "11101"},
    {"name": "Trends Dispensaries LLC", "address": "2721 44th Dr", "city": "Long Island City", "zip": "11101"},
    {"name": "Native Haze Cannabis Co. LLC", "address": "1503 Canandaigua Rd, Suite 3B & 3C", "city": "Macedon", "zip": "14502"},
    {"name": "P. Nuggs LLC", "address": "236 Meehan Rd, Suite 1", "city": "Malone", "zip": "12953"},
    {"name": "Cream Luxuries Astoria Inc.", "address": "5 Division St", "city": "Manhattan", "zip": "10002"},
    {"name": "JUST BREATHE SYRACUSE", "address": "185 W Seneca St", "city": "Manlius", "zip": "13104"},
    {"name": "Flower Power Dispensers", "address": "7110 Grand Ave", "city": "Maspeth", "zip": "11378"},
    {"name": "Joint Venture Cannabis Dispensary", "address": "2 Munsell Road", "city": "Medford", "zip": "11763"},
    {"name": "OFFICIAL JJM INC.", "address": "262 Middle Island Rd", "city": "Medford", "zip": "11763"},
    {"name": "Bloom Brothers", "address": "442 Broadway", "city": "Menands", "zip": "12204"},
    {"name": "Northern Lights NY", "address": "90 Broadway Spc 8", "city": "Menands", "zip": "12204"},
    {"name": "The Cannabis Place", "address": "74-03 Metropolitan Avenue", "city": "Middle VIllage", "zip": "11379"},
    {"name": "Rosebud Club LLC", "address": "400 North Galleria Drive", "city": "Middletown", "zip": "10941"},
    {"name": "Monticello Cannabis LLC", "address": "73 Pleasant St", "city": "Monticello", "zip": "12701"},
    {"name": "Elevate Cannabis", "address": "127 S Terrace Ave", "city": "Mount Vernon", "zip": "10550"},
    {"name": "Joint Venture 1111 LLC", "address": "9 Gramatan Ave", "city": "Mount Vernon", "zip": "10550"},
    {"name": "Nuna Harvest LLC", "address": "696 Locust St", "city": "Mount Vernon", "zip": "10552"},
    {"name": "844 Route 211 LLC", "address": "1326 County Route 12", "city": "New Hampton", "zip": "10958"},
    {"name": "The Village Green Dispensary", "address": "New Hartford Shopping Ctr", "city": "New Hartford", "zip": "13413"},
    {"name": "October Basics, LLC", "address": "4790 Commercial Dr", "city": "New Hartford", "zip": "13413"},
    {"name": "HerbHub LLC", "address": "272-06 UNION TURNPIKE", "city": "New Hyde Park", "zip": "11040"},
    {"name": "BIG GAS DISPENSARY", "address": "98 N Chestnut St", "city": "New Paltz", "zip": "12561"},
    {"name": "Farmers Choice Dispensary 2 LLC", "address": "1 Old Route 299", "city": "New Paltz", "zip": "12561"},
    {"name": "Eshe Holdings LLC", "address": "576 North Ave", "city": "New Rochelle", "zip": "10801"},
    {"name": "Highlife Health, LLC", "address": "19 Huguenot St", "city": "New Rochelle", "zip": "10801"},
    {"name": "The Cannabis Reserve", "address": "1307 North Ave", "city": "New Rochelle", "zip": "10804"},
    {"name": "Monarch Reserve", "address": "251 North Ave", "city": "New Rochelle", "zip": "10801"},
    {"name": "Soulful Matter LLC", "address": "365B North Ave", "city": "New Rochelle", "zip": "10801"},
    {"name": "Sunny Days Dispensary LLC", "address": "20 E Main St", "city": "New Rochelle", "zip": "10801"},
    {"name": "115 Corner LLC", "address": "345 E 115th St", "city": "New York", "zip": "10029"},
    {"name": "Charlie Fox", "address": "719 7th Ave", "city": "New York", "zip": "10036"},
    {"name": "SMILEY EXOTICS", "address": "201 E 30th St", "city": "New York", "zip": "10016"},
    {"name": "2147 44th LLC", "address": "1720 2nd Ave", "city": "New York", "zip": "10128"},
    {"name": "The Flower Pot", "address": "459 Lexington Ave", "city": "New York", "zip": "10017"},
    {"name": "69 Graham Dispensary LLC", "address": "12 W 18th St", "city": "New York", "zip": "10011"},
    {"name": "JUST A LITTLE HIGHER MURRAY HILL", "address": "698 2nd Ave", "city": "New York", "zip": "10016"},
    {"name": "AA 301 W. 45th St Inc.", "address": "743 9th Ave", "city": "New York", "zip": "10019"},
    {"name": "The Flowery", "address": "2465 Broadway", "city": "New York", "zip": "10025"},
    {"name": "Chelsea Cannabis Co.", "address": "104 7th Ave", "city": "New York", "zip": "10011"},
    {"name": "Authentic 212 LLC", "address": "474 Fashion Ave", "city": "New York", "zip": "10018"},
    {"name": "Bellanova", "address": "331 East 9th St.", "city": "New York", "zip": "10003"},
    {"name": "Balagan Cannabis NY LLC", "address": "440 10th Ave", "city": "New York", "zip": "10001"},
    {"name": "Gotham Chelsea", "address": "146 10th Ave", "city": "New York", "zip": "10011"},
    {"name": "The Alchemy", "address": "302 8th Ave", "city": "New York", "zip": "10001"},
    {"name": "Alta Dispensary", "address": "52A Kenmare St", "city": "New York", "zip": "10012"},
    {"name": "Blue Forest Farms Dispensary LLC", "address": "122 E 25th St", "city": "New York", "zip": "10010"},
    {"name": "Bright Elephant, LLC", "address": "206 8th Ave", "city": "New York", "zip": "10011"},
    {"name": "Bud & Honey Dispensary Inc.", "address": "241 5th Ave", "city": "New York", "zip": "10016"},
    {"name": "CANNADREAMS INC.", "address": "862 9th Ave", "city": "New York", "zip": "10019"},
    {"name": "CANNAISSEUR NY LLC", "address": "317 10th Ave", "city": "New York", "zip": "10001"},
    {"name": "CNBS27 Inc.", "address": "383 8th Ave", "city": "New York", "zip": "10001"},
    {"name": "CONBUD LLC", "address": "85 Delancey St", "city": "New York", "zip": "10002"},
    {"name": "DAGGA LLC", "address": "157 W 72nd St", "city": "New York", "zip": "10023"},
    {"name": "Lighthouse Cannabis", "address": "381 Broadway", "city": "New York", "zip": "10013"},
    {"name": "Diamond Star Group inc.", "address": "85 Nassau Street", "city": "New York", "zip": "10038"},
    {"name": "Divine Kinnektion LLC", "address": "2610 Broadway Ave", "city": "New York", "zip": "10025"},
    {"name": "Paint Puff N' Peace", "address": "2119 Frederick Douglass Blvd", "city": "New York", "zip": "10026"},
    {"name": "EXCITE UNLIMITED LLC", "address": "4441 BROADWAY", "city": "New York", "zip": "10040"},
    {"name": "Fluent", "address": "242 East 58th St.", "city": "New York", "zip": "10022"},
    {"name": "Bad Maryjane", "address": "799 Lexington Ave", "city": "New York", "zip": "10065"},
    {"name": "Fire Escape", "address": "103 Avenue A", "city": "New York", "zip": "10009"},
    {"name": "Dazed", "address": "33 Union Sq W", "city": "New York", "zip": "10003"},
    {"name": "Flower Power Dispensers", "address": "22 W 66th St", "city": "New York", "zip": "10023"},
    {"name": "Free Thinkers LLC", "address": "2 Coenties Slip", "city": "New York", "zip": "10004"},
    {"name": "Culture House", "address": "958 Avenue of the Americas", "city": "New York", "zip": "10001"},
    {"name": "Gotham Bowery", "address": "3 E 3rd St", "city": "New York", "zip": "10003"},
    {"name": "GRAPE STOMPER LLC", "address": "2273A Broadway", "city": "New York", "zip": "10024"},
    {"name": "Gotham Buds LLC", "address": "248 W 125th St", "city": "New York", "zip": "10027"},
    {"name": "Emerald Dispensary", "address": "1190 Lexington Ave", "city": "New York", "zip": "10028"},
    {"name": "Green Rise Inc.", "address": "599 10th Ave", "city": "New York", "zip": "10036"},
    {"name": "Griffon Cannabis LLC", "address": "741 Columbus Ave", "city": "New York", "zip": "10025"},
    {"name": "H&O CITY HEART", "address": "362 WEST 125TH STREET", "city": "New York", "zip": "10027"},
    {"name": "THE FLOWERY", "address": "101 E 10th St", "city": "New York", "zip": "10003"},
    {"name": "HEALTHY CHOICE SEAVIEW LLC", "address": "3858 Broadway retail", "city": "New York", "zip": "10032"},
    {"name": "HORNBILL INC.", "address": "224 1st Ave", "city": "New York", "zip": "10009"},
    {"name": "HOUSING WORKS CANNABIS, LLC", "address": "750 Broadway", "city": "New York", "zip": "10003"},
    {"name": "Indoor Treez Corp.", "address": "584 8th Ave", "city": "New York", "zip": "10018"},
    {"name": "Juniper NY LLC", "address": "229 Avenue B", "city": "New York", "zip": "10009"},
    {"name": "KVSSQ Consulting LLC", "address": "1280 1st Ave", "city": "New York", "zip": "10065"},
    {"name": "KushKlub NY LLC", "address": "186 Orchard St", "city": "New York", "zip": "10002"},
    {"name": "Housing Works Cannabis Co.", "address": "846 Avenue of the Americas", "city": "New York", "zip": "10001"},
    {"name": "ELEVATION HEADQUARTERS", "address": "701 8th Ave", "city": "New York", "zip": "10036"},
    {"name": "Leafy NYC II LLC", "address": "245 W 14th St", "city": "New York", "zip": "10011"},
    {"name": "NYC Bud Midtown", "address": "405 W 39th St", "city": "New York", "zip": "10018"},
    {"name": "Luxe Leaf Boutique LLC", "address": "820 2nd Ave", "city": "New York", "zip": "10017"},
    {"name": "MIDNIGHT MOON CORP", "address": "1536 Amsterdam Ave", "city": "New York", "zip": "10031"},
    {"name": "Green Genius NYC", "address": "214 3rd Ave", "city": "New York", "zip": "10003"},
    {"name": "Mighty Lucky Inc.", "address": "259 Bowery", "city": "New York", "zip": "10002"},
    {"name": "Rezidue", "address": "723 11th Ave", "city": "New York", "zip": "10019"},
    {"name": "MoxBeacon LLC", "address": "2379 Broadway", "city": "New York", "zip": "10024"},
    {"name": "Elevate Soho Cannabis", "address": "481 Broadway", "city": "New York", "zip": "10013"},
    {"name": "NY Retail 5 Inc.", "address": "519 Madison Ave", "city": "New York", "zip": "10022"},
    {"name": "NYC Green Girl LLC", "address": "58-60 Ninth Avenue", "city": "New York", "zip": "10011"},
    {"name": "Tetra", "address": "2152 3rd Ave", "city": "New York", "zip": "10035"},
    {"name": "Nucleus Dispensary Inc.", "address": "1819 2nd Ave", "city": "New York", "zip": "10128"},
    {"name": "G Spot NYC", "address": "977 2nd Ave", "city": "New York", "zip": "10022"},
    {"name": "PACIFIC PALMS GROUP LLC", "address": "345 Greenwich St", "city": "New York", "zip": "10013"},
    {"name": "Nicklz", "address": "797 8th Ave", "city": "New York", "zip": "10019"},
    {"name": "Polanco Brothers Corp", "address": "12 E 42nd St", "city": "New York", "zip": "10017"},
    {"name": "Pure Blossoms LLC", "address": "716 Amsterdam Ave", "city": "New York", "zip": "10025"},
    {"name": "QUBE", "address": "1412 Broadway", "city": "New York", "zip": "10018"},
    {"name": "Dagmar Cannabis", "address": "412 W Broadway", "city": "New York", "zip": "10012"},
    {"name": "Metro Leaf", "address": "2742 Broadway", "city": "New York", "zip": "10025"},
    {"name": "Pryzm", "address": "15 Avenue B", "city": "New York", "zip": "10009"},
    {"name": "VERDI", "address": "158 W 23rd St", "city": "New York", "zip": "10011"},
    {"name": "ASTORIA HERB AND HIVE", "address": "653 9th Ave", "city": "New York", "zip": "10036"},
    {"name": "Altocanna", "address": "110 Chambers St", "city": "New York", "zip": "10007"},
    {"name": "Sith Lord TD Inc.", "address": "381 5th Ave", "city": "New York", "zip": "10016"},
    {"name": "Sky High Club LLC", "address": "129 Avenue C", "city": "New York", "zip": "10009"},
    {"name": "Smacked LLC", "address": "144 Bleecker St", "city": "New York", "zip": "10012"},
    {"name": "The Flowery", "address": "70 Canal St", "city": "New York", "zip": "10002"},
    {"name": "Sparkboro Inc", "address": "704 W 177th St", "city": "New York", "zip": "10033"},
    {"name": "Sparkology NY LLC", "address": "1870 3rd Ave", "city": "New York", "zip": "10029"},
    {"name": "Statis NY Holdings LLC", "address": "111 Fulton St", "city": "New York", "zip": "10038"},
    {"name": "Strains for Life Powered by Indoor Treez", "address": "3543 Broadway # 3547", "city": "New York", "zip": "10031"},
    {"name": "Superfly Dispensary LLC", "address": "57 W 86th St", "city": "New York", "zip": "10024"},
    {"name": "Stoops NYC", "address": "182 5th Ave", "city": "New York", "zip": "10010"},
    {"name": "THE TRAVEL AGENCY SOHO", "address": "598 Broadway", "city": "New York", "zip": "10012"},
    {"name": "Erbquest", "address": "52 W 27th St", "city": "New York", "zip": "10001"},
    {"name": "SOFACLUB CANNABIS", "address": "127 E 56th St", "city": "New York", "zip": "10022"},
    {"name": "THE CLUB ZAZA LLC", "address": "369 7th Ave", "city": "New York", "zip": "10001"},
    {"name": "THE HERBAL CARE THC LLC", "address": "1412 Lexington Ave", "city": "New York", "zip": "10128"},
    {"name": "Terrapin Greens", "address": "587 5th Ave", "city": "New York", "zip": "10017"},
    {"name": "The Cannabis Spot Inc.", "address": "386 Canal st", "city": "New York", "zip": "10013"},
    {"name": "Union Square Travel Agency: A Cannabis Store", "address": "835 Broadway", "city": "New York", "zip": "10003"},
    {"name": "The Gibbons Group LLC", "address": "2459 Frederick Douglass Blvd", "city": "New York", "zip": "10027"},
    {"name": "The Hootch LLC", "address": "1662  First  Avenue", "city": "New York", "zip": "10028"},
    {"name": "Twinn Leaf LLC", "address": "566 7th Ave", "city": "New York", "zip": "10018"},
    {"name": "Happy Munkey", "address": "151 Dyckman St", "city": "New York", "zip": "10040"},
    {"name": "The Flowery", "address": "112 Christopher St", "city": "New York", "zip": "10014"},
    {"name": "Liberty Buds", "address": "1115 1st Ave", "city": "New York", "zip": "10065"},
    {"name": "Weedish LLC", "address": "128 E 86th St", "city": "New York", "zip": "10028"},
    {"name": "Lenox Hill Cannabis Co.", "address": "334 E 73rd St", "city": "New York", "zip": "10021"},
    {"name": "Yogikrupa 171 LLC", "address": "171 W 4th St", "city": "New York", "zip": "10014"},
    {"name": "Elevated Times-1 LLC", "address": "1173 E Union St", "city": "Newark", "zip": "14513"},
    {"name": "Haze and Harvest", "address": "6740 State Route 31 E", "city": "Newark", "zip": "14513"},
    {"name": "GREEN LEAF", "address": "1400 Route 300", "city": "Newburgh", "zip": "12550"},
    {"name": "Cannabliss Recreational LLC", "address": "217 S Plank Rd", "city": "Newburgh", "zip": "12550"},
    {"name": "The Flowery", "address": "142 Route 17K", "city": "Newburgh", "zip": "12550"},
    {"name": "Curaleaf NY, LLC", "address": "8 North Plank Rd.", "city": "Newburgh", "zip": "12550"},
    {"name": "Gift Leaf 676 LLC", "address": "1663 Route 300", "city": "Newburgh", "zip": "12550"},
    {"name": "Green Galore LLC", "address": "1930 Route 300", "city": "Newburgh", "zip": "12550"},
    {"name": "Guru Baba Inc", "address": "5306 Route 9W", "city": "Newburgh", "zip": "12550"},
    {"name": "HAPPY TREE LLC", "address": "99 Route 17K Ste 2", "city": "Newburgh", "zip": "12550"},
    {"name": "JJSK INC.", "address": "165 S Plank Rd", "city": "Newburgh", "zip": "12550"},
    {"name": "NNC 2 LLC", "address": "496 Broadway", "city": "Newburgh", "zip": "12550"},
    {"name": "RawLeaf Enterprises LLC", "address": "364 Broadway", "city": "Newburgh", "zip": "12550"},
    {"name": "Zootiez LLC", "address": "5440 Route 9W", "city": "Newburgh", "zip": "12550"},
    {"name": "White Atmoss", "address": "136 Lake St Ste 2", "city": "Newburgh", "zip": "12550"},
    {"name": "RT 13 CANNABIS NOVELTIES LLC", "address": "2586 Elmira Rd", "city": "Newfield", "zip": "14867"},
    {"name": "LEAFFIELD, LLC", "address": "7101 Packard Rd", "city": "Niagara", "zip": "14304"},
    {"name": "Cannabis Dispensary LLC", "address": "7560 Niagara Falls Blvd", "city": "Niagara Falls", "zip": "14304"},
    {"name": "Carry-On Cannabis NY LLC", "address": "8529 Niagara Falls Blvd", "city": "Niagara Falls", "zip": "14304"},
    {"name": "L A FFOCA LLC", "address": "1618 18th St", "city": "Niagara Falls", "zip": "14305"},
    {"name": "Green Market", "address": "2445 Allen Ave", "city": "Niagara Falls", "zip": "14303"},
    {"name": "Upstate Exotics", "address": "9200 Niagara Falls Blvd", "city": "Niagara Falls", "zip": "14304"},
    {"name": "Flynnstoned Cannabis Company", "address": "3711 Brewerton Rd Ste 8-10", "city": "North Syracuse", "zip": "13212"},
    {"name": "Herb-Z", "address": "109 E Taft Rd", "city": "North Syracuse", "zip": "13212"},
    {"name": "Love Nug, LLC", "address": "3176 Niagara Falls Blvd", "city": "North Tonawanda", "zip": "14120"},
    {"name": "Satisfied Mind", "address": "31 Webster St", "city": "North Tonawanda", "zip": "14120"},
    {"name": "Treehouse Cannabis", "address": "28 Route 59", "city": "Nyack", "zip": "10960"},
    {"name": "SANAT CARDS & GIFTS INC", "address": "214 24 73rd Ave", "city": "OAKLAND GARDEN", "zip": "11364"},
    {"name": "Silky Strain", "address": "224-15 union Turnpike", "city": "Oakland gardens", "zip": "11364"},
    {"name": "The Green Door Dispensary", "address": "3748 State Highway 37", "city": "Ogdensburg", "zip": "13669"},
    {"name": "Jupter Cafe", "address": "172 N Union St", "city": "Olean", "zip": "14760"},
    {"name": "Dosha Farms", "address": "76 Main St", "city": "Oneonta", "zip": "13820"},
    {"name": "Rochester Management Hospitality Group, Inc.", "address": "1873 State Route 104", "city": "Ontario", "zip": "14519"},
    {"name": "Best Buds Thirteen LLC", "address": "50 N Highland Ave", "city": "Ossining", "zip": "10562"},
    {"name": "Brow & Body LLC", "address": "345 N Highland Ave", "city": "Ossining", "zip": "10562"},
    {"name": "Crown and Gavel LLC", "address": "34 Main St", "city": "Ossining", "zip": "10562"},
    {"name": "Bud Dispensary Company, LLC", "address": "143 George St", "city": "Oswego", "zip": "13126"},
    {"name": "MEADOW FLOWER LLC", "address": "208 Front St", "city": "Owego", "zip": "13827"},
    {"name": "Flor de Fred", "address": "9605 Liberty Ave", "city": "Ozone Park", "zip": "11417"},
    {"name": "GREEN FLOWER WELLNESS", "address": "8508 Pitkin Ave", "city": "Ozone Park", "zip": "11417"},
    {"name": "GREEN STRAIN RELAXATION CORP", "address": "107-31 Liberty Ave", "city": "Ozone Park", "zip": "11417"},
    {"name": "Gourmet Budz LLC", "address": "135-26 Crossbay Blvd", "city": "Ozone Park", "zip": "11417"},
    {"name": "HB&V ENTERPRISES INC", "address": "615 Route 112", "city": "Patchogue", "zip": "11772"},
    {"name": "Cloud 914", "address": "807 Washington St", "city": "Peekskill", "zip": "10566"},
    {"name": "Piffords Inc", "address": "500 Highland Ave", "city": "Peekskill", "zip": "10566"},
    {"name": "Valley Greens Ltd.", "address": "939 Central Ave", "city": "Peekskill", "zip": "10566"},
    {"name": "Bloom Cannabis Dispensary", "address": "242 Lake Street Plz", "city": "Penn Yan", "zip": "14527"},
    {"name": "Highland Gallery LLC", "address": "501 Route 9W", "city": "Piermont", "zip": "10968"},
    {"name": "Two Budz LLC", "address": "7723 S Main St", "city": "Pine Plains", "zip": "12567"},
    {"name": "The Grass Hole Cannabis", "address": "779 State Route 3", "city": "Plattsburgh", "zip": "12901"},
    {"name": "Curaleaf NY, LLC", "address": "345 Cornelia St", "city": "Plattsburgh", "zip": "12901"},
    {"name": "The Herb Cave, LLC", "address": "519 State Route 3", "city": "Plattsburgh", "zip": "12901"},
    {"name": "DeMarino's, LLC", "address": "110 Jersey Ave", "city": "Port Jervis", "zip": "12771"},
    {"name": "Heavenly Garden NY INC", "address": "279 East Main St", "city": "Port Jervis", "zip": "12771"},
    {"name": "Puff and Pump, L.L.C.", "address": "6-8 Hammond St", "city": "Port Jervis", "zip": "12771"},
    {"name": "Dune Lilly, LLC", "address": "185 Market St", "city": "Potsdam", "zip": "13676"},
    {"name": "THE FIREHAUS NY", "address": "7479 US Highway 11", "city": "Potsdam", "zip": "13676"},
    {"name": "BALLI CANN, INC.", "address": "248 Smith St", "city": "Poughkeepsie", "zip": "12601"},
    {"name": "Grounded", "address": "3665 Albany Post Rd", "city": "Poughkeepsie", "zip": "12601"},
    {"name": "Best Buds of New York, Inc.", "address": "4-10 Taft Avenue", "city": "Poughkeepsie", "zip": "12603"},
    {"name": "Black Market Canna Co LLC", "address": "89 Main St", "city": "Poughkeepsie", "zip": "12601"},
    {"name": "Dutchess Roots LLC", "address": "2615 South Rd", "city": "Poughkeepsie", "zip": "12601"},
    {"name": "Serenity Greens LLC", "address": "2245 South Rd", "city": "Poughkeepsie", "zip": "12601"},
    {"name": "Purple Plains", "address": "32 Westchester Ave", "city": "Pound Ridge", "zip": "10576"},
    {"name": "CL Canna Holdings, LLC", "address": "3808 State Route 13", "city": "Pulaski", "zip": "13142"},
    {"name": "AAR CANN LLC", "address": "110-04 Jamaica Ave", "city": "Queens", "zip": "11418"},
    {"name": "Dankley Canna", "address": "21917 Hillside Ave", "city": "Queens Village", "zip": "11427"},
    {"name": "FUMI Dispensary LLC", "address": "217-12 Hempstead Ave", "city": "Queens Village", "zip": "11429"},
    {"name": "LIMITLESS THOUGHTS LLC", "address": "9107 Springfield Blvd", "city": "Queens Village", "zip": "11428"},
    {"name": "C&R Project LLC", "address": "366 Quaker Rd", "city": "Queensbury", "zip": "12804"},
    {"name": "HIGH ROLLERS CANNABIS", "address": "909 State Route 9, Suite #3", "city": "Queensbury", "zip": "12804"},
    {"name": "Nicless LLC", "address": "704 Upper Glen St", "city": "Queensbury", "zip": "12804"},
    {"name": "Upstate Pines", "address": "7345 S Broadway", "city": "Red Hook", "zip": "12571"},
    {"name": "65-55 Woodhaven Licensing LLC", "address": "65-55 Woodhaven Blvd", "city": "Rego Park", "zip": "11374"},
    {"name": "BazzJAT Retail Inc", "address": "9538 Queens Blvd", "city": "Rego Park", "zip": "11374"},
    {"name": "NATURAL LEAF INC.", "address": "9848 Queens Blvd", "city": "Rego Park", "zip": "11374"},
    {"name": "THE GOAT DISPENSARY", "address": "6308 Woodhaven Blvd", "city": "Rego Park", "zip": "11374"},
    {"name": "Token Retail Inc", "address": "9229 Queens Blvd", "city": "Rego Park", "zip": "11374"},
    {"name": "High Frequency", "address": "96 Columbia St", "city": "Rensselaer", "zip": "12144"},
    {"name": "Stage One Cannabis LLC", "address": "810C Broadway", "city": "Rensselaer", "zip": "12144"},
    {"name": "Broadway Bud", "address": "116-05 Metropolitan Ave", "city": "Richmond Hill", "zip": "11418"},
    {"name": "Caurd Wellness LLC", "address": "465 Onderdonk Ave", "city": "Ridgewood", "zip": "11385"},
    {"name": "Juicy Wellness Inc.", "address": "6633 Fresh Pond Rd", "city": "Ridgewood", "zip": "11385"},
    {"name": "Late Bloomers NYC LLC", "address": "57-01 Myrtle Avenue", "city": "Ridgewood", "zip": "11385"},
    {"name": "Seneca Cannabis", "address": "662 Seneca Ave", "city": "Ridgewood", "zip": "11385"},
    {"name": "Metropolis Cannabis", "address": "1086 Old Country Rd", "city": "Riverhead", "zip": "11901"},
    {"name": "Kaur Consulting LLC", "address": "1871 Old Country Rd", "city": "Riverhead", "zip": "11901"},
    {"name": "Tink & E Co. Inc.", "address": "1201 Ostrander Ave", "city": "Riverhead", "zip": "11901"},
    {"name": "720 winton road LLC", "address": "722 N Winton Rd", "city": "Rochester", "zip": "14609"},
    {"name": "Azzam Properties LLC", "address": "499 Monroe Ave", "city": "Rochester", "zip": "14607"},
    {"name": "BUDDEEZ LLC", "address": "1460 Lyell Ave Ste 200", "city": "Rochester", "zip": "14606"},
    {"name": "Benjamin E Botach", "address": "35 Chestnut St", "city": "Rochester", "zip": "14604"},
    {"name": "Happy Goat Dispensary", "address": "1330 Mount Hope Ave", "city": "Rochester", "zip": "14620"},
    {"name": "Cannabis Corner", "address": "2227 Clifford Ave", "city": "Rochester", "zip": "14609"},
    {"name": "Rise", "address": "556 Jefferson Road", "city": "Rochester", "zip": "14623"},
    {"name": "Green Comfort Inc.", "address": "999 S Clinton Ave", "city": "Rochester", "zip": "14620"},
    {"name": "Flynnstoned Cannabis Company", "address": "714 W Ridge Rd", "city": "Rochester", "zip": "14615"},
    {"name": "Happy Dayz Cannabis Dispensary", "address": "74 Lake Ave", "city": "Rochester", "zip": "14608"},
    {"name": "High End New York", "address": "545 Clinton Ave S", "city": "Rochester", "zip": "14620"},
    {"name": "Lisa Birnbaum Personal Training, LLC", "address": "125 State St", "city": "Rochester", "zip": "14614"},
    {"name": "Good Life Collective", "address": "155 Monroe Ave", "city": "Rochester", "zip": "14607"},
    {"name": "ZenZo", "address": "1900 Empire Blvd", "city": "Rochester", "zip": "14580"},
    {"name": "MJ Dispensary LLC", "address": "900 Jefferson Rd Ste 902", "city": "Rochester", "zip": "14623"},
    {"name": "Society of the Seven Sages", "address": "656 South Ave", "city": "Rochester", "zip": "14620"},
    {"name": "not applicable at the moment", "address": "400 Jefferson Rd, Ste 2", "city": "Rochester", "zip": "14623"},
    {"name": "The Shady Grove Dispensary", "address": "3047 W Henrietta Rd", "city": "Rochester", "zip": "14623"},
    {"name": "Pure Wellness Dispensary LLC", "address": "360 W Ridge Rd", "city": "Rochester", "zip": "14615"},
    {"name": "Roc Sole Sanctuary, LLC", "address": "1430 Dewey Ave", "city": "Rochester", "zip": "14615"},
    {"name": "Serenity Now Dispensary", "address": "1150 University Ave", "city": "Rochester", "zip": "14607"},
    {"name": "Trugenetix Inc", "address": "802 Monroe Ave", "city": "Rochester", "zip": "14607"},
    {"name": "Wonderland Dispensary Corp", "address": "545 W Ridge Rd", "city": "Rochester", "zip": "14615"},
    {"name": "Platinum Leaf LLC", "address": "196 Rock Hill Dr", "city": "Rock Hill", "zip": "12775"},
    {"name": "Munchie's Dispensary NY LLC", "address": "8701 Rockaway Beach Blvd", "city": "Rockaway Beach", "zip": "11693"},
    {"name": "ROCKAWAY BEACH CAFE INC.", "address": "114-19 Rockaway Beach Blvd", "city": "Rockaway Park", "zip": "11694"},
    {"name": "Copper City Bud LLC", "address": "319 S James St", "city": "Rome", "zip": "13440"},
    {"name": "High Society", "address": "1326 Erie Blvd W", "city": "Rome", "zip": "13440"},
    {"name": "Luxus Botanica", "address": "8234 Turin Rd Ste 1", "city": "Rome", "zip": "13440"},
    {"name": "Green Glee", "address": "247-14 South Conduit Avenue", "city": "Rosedale", "zip": "11422"},
    {"name": "Hudson Park Agency LLC", "address": "14407 243rd St", "city": "Rosedale", "zip": "11422"},
    {"name": "Mocha Joint Corp", "address": "25102 Rockaway Blvd", "city": "Rosedale", "zip": "11422"},
    {"name": "Rosedale Cannabis Dispensary LLC", "address": "245-02 Merrick Blvd", "city": "Rosedale", "zip": "11422"},
    {"name": "Canna Health and Wellness,LLC", "address": "6075 E Henrietta Rd", "city": "Rush", "zip": "14543"},
    {"name": "EVERYTHING EXOTIC DELI CORP", "address": "109-30 MERRICK BLVd", "city": "SOUTH JAMAICA", "zip": "11433"},
    {"name": "Elevate ADK", "address": "622 Lake Flower Ave.", "city": "Saranac Lake", "zip": "12983"},
    {"name": "Harvester's Market LLC", "address": "1164 New York Route 29", "city": "Saratoga", "zip": "12871"},
    {"name": "High Peaks Canna Inc.", "address": "137 Maple Ave", "city": "Saratoga Springs", "zip": "12866"},
    {"name": "Reverie 73 NY LLC", "address": "1 Kaydeross Ave W", "city": "Saratoga Springs", "zip": "12866"},
    {"name": "Spa City Cannabis LLC", "address": "75 Weibel Ave", "city": "Saratoga Springs", "zip": "12866"},
    {"name": "The F4 LLC", "address": "67 West Ave", "city": "Saratoga Springs", "zip": "12866"},
    {"name": "On The Move Contracting Services, LLC", "address": "1635 N Main St", "city": "Savannah", "zip": "13146"},
    {"name": "1650 CRANE STREET DISPENSARY LLC", "address": "1650 Crane St Ste 1", "city": "Schenectady", "zip": "12303"},
    {"name": "Cloud 9 Evolution LLC", "address": "1610 Eastern Pkwy", "city": "Schenectady", "zip": "12309"},
    {"name": "Cussin's Cannabis", "address": "2075 Central Ave", "city": "Schenectady", "zip": "12304"},
    {"name": "Upstate CBD", "address": "1613 Union Street", "city": "Schenectady", "zip": "12309"},
    {"name": "Electric City Cannabis Co, LLC", "address": "1354 Lower Broadway", "city": "Schenectady", "zip": "12306"},
    {"name": "Mill Lane Provisions, LLC", "address": "102 State St", "city": "Schenectady", "zip": "12305"},
    {"name": "Ripe Cannabis (Assumed Name ID #: 7224450)", "address": "245 Broadway, Suite 4", "city": "Schenectady", "zip": "12305"},
    {"name": "Planet Green Dispensary and Supply", "address": "1738 State St", "city": "Schenectady", "zip": "12304"},
    {"name": "Smokey Jungle LLC", "address": "330 Becker Dr", "city": "Schenectady", "zip": "12306"},
    {"name": "The Weed Spot LLC", "address": "501 State St", "city": "Schenectady", "zip": "12305"},
    {"name": "Cannabicity", "address": "220 Harborside Dr Ste 111", "city": "Schenectady", "zip": "12305"},
    {"name": "Bud Brothers and Sisters LLC", "address": "1649 Columbia Tpke", "city": "Schodack", "zip": "12033"},
    {"name": "1110 NAMO INC", "address": "1110 Middle Country Rd", "city": "Selden", "zip": "11784"},
    {"name": "Just Breathe Finger Lakes", "address": "2988 US Route 20", "city": "Seneca Falls", "zip": "13148"},
    {"name": "LUCIFER BREWING CORPORATION", "address": "79 Fall St", "city": "Seneca Falls", "zip": "13148"},
    {"name": "Tridentru", "address": "131-135 Saratoga Avenue", "city": "South Glens Falls", "zip": "12803"},
    {"name": "Alyssa M Renko", "address": "320 South Transit Rd", "city": "South Lockport", "zip": "14094"},
    {"name": "Jackpot Daily", "address": "10919 Rockaway Blvd", "city": "South Ozone Park", "zip": "11420"},
    {"name": "Big City Flavors", "address": "11119 Liberty Ave", "city": "South Richmond Hill", "zip": "11419"},
    {"name": "HVK Management, LLC", "address": "130-4 Atlantic Avenue", "city": "South Richmond Hill", "zip": "11419"},
    {"name": "Vaporize, Inc.", "address": "12420 Liberty Ave", "city": "South Richmond Hill", "zip": "11419"},
    {"name": "East End Arrivals", "address": "471 County Road 39 # CR-39", "city": "Southampton", "zip": "11968"},
    {"name": "Brown Budda New York", "address": "1533 County Road 39", "city": "Southampton", "zip": "11968"},
    {"name": "The Hamptons Collective", "address": "257 County Road 39A", "city": "Southampton", "zip": "11968"},
    {"name": "Southampton Deep Blue Sea LLC", "address": "125 Tuckahoe Ln", "city": "Southampton", "zip": "11968"},
    {"name": "Deep XY Holding LLC", "address": "10 Montauk Highway", "city": "Southhampton", "zip": "11977"},
    {"name": "CannaBliss Recreational Marijuana Dispensary LLC", "address": "377 S. Union St.", "city": "Spencerport", "zip": "14559"},
    {"name": "AJA Cannabis 1010 LLC", "address": "2 S Central Ave", "city": "Spring Valley", "zip": "10977"},
    {"name": "Cannabis Company of New York LLC", "address": "76 Route 59", "city": "Spring Valley", "zip": "10977"},
    {"name": "581 Realty CRD LLC", "address": "22206 S Conduit Ave", "city": "Springfield Gardens", "zip": "11413"},
    {"name": "Stash Box", "address": "23004 S Conduit Ave", "city": "Springfield Gardens", "zip": "11413"},
    {"name": "Dance Like A Star With Serge, Inc.", "address": "29 N Cascade Dr", "city": "Springville", "zip": "14141"},
    {"name": "960 bloomingdale road LLC", "address": "2059 Richmond Ave", "city": "Staten Island", "zip": "10314"},
    {"name": "A Cannaful Life LLC", "address": "1547 Arthur Kill Road", "city": "Staten Island", "zip": "10312"},
    {"name": "Highstone", "address": "1938 Clove Rd", "city": "Staten Island", "zip": "10304"},
    {"name": "Be.", "address": "338 New Dorp Lane", "city": "Staten Island", "zip": "10306"},
    {"name": "OZ Dispensary", "address": "956 Jewett Ave", "city": "Staten Island", "zip": "10314"},
    {"name": "Clouditude Dispensary", "address": "4034 Hylan Blvd", "city": "Staten Island", "zip": "10308"},
    {"name": "East End Ventures I LLC", "address": "3295 Richmond Ave", "city": "Staten Island", "zip": "10312"},
    {"name": "GEORGIA HEIGHTS, LLC", "address": "755 Forest Ave", "city": "Staten Island", "zip": "10310"},
    {"name": "Gaslight Dispensary", "address": "465 Forest Ave", "city": "Staten Island", "zip": "10301"},
    {"name": "Green Land Retail LLC", "address": "3115 Victory Blvd", "city": "Staten Island", "zip": "10314"},
    {"name": "Green Plan Source, Inc.", "address": "1172 Victory Blvd # 4", "city": "Staten Island", "zip": "10301"},
    {"name": "Luisa Bella Holdings, LLC", "address": "35 Page Ave", "city": "Staten Island", "zip": "10309"},
    {"name": "Nitecap LLC", "address": "1151 Hylan Blvd", "city": "Staten Island", "zip": "10305"},
    {"name": "NugHub NY LLC", "address": "1350 Forest Ave", "city": "Staten Island", "zip": "10302"},
    {"name": "Happy Times Cannabis Co.", "address": "1399 Hylan Blvd", "city": "Staten Island", "zip": "10305"},
    {"name": "The Flowery", "address": "3022 Veterans Rd W", "city": "Staten Island", "zip": "10309"},
    {"name": "SLA Services INC", "address": "570 -574 Midland Ave", "city": "Staten Island", "zip": "10306"},
    {"name": "ZenZest LLC", "address": "2343 Forest Ave", "city": "Staten Island", "zip": "10303"},
    {"name": "RENAISSANT NYC", "address": "4007 Queens Blvd # A", "city": "Sunnyside", "zip": "11104"},
    {"name": "Thrive Syracuse", "address": "3065 Erie Blvd E", "city": "Syracuse", "zip": "13224"},
    {"name": "Create Kindness LLC", "address": "911 N Salina St", "city": "Syracuse", "zip": "13208"},
    {"name": "Diamond Tree Dispensary", "address": "2700 Erie Blvd E", "city": "Syracuse", "zip": "13224"},
    {"name": "Equity Max Property Management, Inc.,", "address": "814 Wolf St", "city": "Syracuse", "zip": "13208"},
    {"name": "FLYNNSTONED", "address": "219 Walton St", "city": "Syracuse", "zip": "13202"},
    {"name": "Green on Top, LLC", "address": "1744 W Genesee St", "city": "Syracuse", "zip": "13204"},
    {"name": "Inside the Park Dispo LLC", "address": "135-137 Marshall St", "city": "Syracuse", "zip": "13210"},
    {"name": "Joe's Buds, LLC", "address": "4658 Onondaga Blvd", "city": "Syracuse", "zip": "13219"},
    {"name": "Loudpack Exotics", "address": "6606 Kinne Rd", "city": "Syracuse", "zip": "13214"},
    {"name": "The Higher Co.", "address": "123 E Willow St", "city": "Syracuse", "zip": "13202"},
    {"name": "Vedaleaf LLC", "address": "2921 Erie Blvd E", "city": "Syracuse", "zip": "13224"},
    {"name": "Wintergreen", "address": "6320 Main St", "city": "Tannersville", "zip": "12485"},
    {"name": "Nipapoa LLC", "address": "51 Main St", "city": "Tarrytown", "zip": "10591"},
    {"name": "Upscale Cannabis Incorporated", "address": "3042b Fenton Ave", "city": "The Bronx", "zip": "10469"},
    {"name": "KB Holdings 716 LLC", "address": "1699 Military Rd", "city": "Tonawanda", "zip": "14217"},
    {"name": "Yeti Canna", "address": "2327 Sheridan Dr", "city": "Tonawanda", "zip": "14150"},
    {"name": "URBAN HERB LLC", "address": "440 Niagara Falls Blvd", "city": "Tonawanda", "zip": "14222"},
    {"name": "art of gas", "address": "3497 Delaware Ave", "city": "Tonawanda", "zip": "14217"},
    {"name": "TRANSCEND WELLNESS PRODUCTS & SERVICES", "address": "289 Oakwood Ave Ste D", "city": "Troy", "zip": "12182"},
    {"name": "Casa Verde Dispensary", "address": "15 Campbell Ave # 2", "city": "Troy", "zip": "12180"},
    {"name": "HOOSICK DISPENSARY", "address": "514 Congress St", "city": "Troy", "zip": "12180"},
    {"name": "420 Bliss", "address": "740 Hoosick Rd", "city": "Troy", "zip": "12180"},
    {"name": "No Name Cannabis Company, LLC", "address": "137 4th St", "city": "Troy", "zip": "12180"},
    {"name": "US Food & Grocery", "address": "1 Northern Dr", "city": "Troy", "zip": "12182"},
    {"name": "Royal Buds LLC", "address": "5 Washington St", "city": "Trumansburg", "zip": "14886"},
    {"name": "Greens Greenery", "address": "54 State Highway 357", "city": "Unadilla", "zip": "13849"},
    {"name": "Air City Cannabis LLC", "address": "1707 Oriskany St W", "city": "Utica", "zip": "13502"},
    {"name": "Capital Cannabis LLC", "address": "930 Oriskany St W", "city": "Utica", "zip": "13502"},
    {"name": "Entropy", "address": "221 Oriskany St E", "city": "Utica", "zip": "13501"},
    {"name": "Exit 31 Exotic", "address": "255 Genesee St", "city": "Utica", "zip": "13501"},
    {"name": "Sacred Bloom", "address": "1308 Vestal Pky E, 1st Floor, Set D", "city": "Vestal", "zip": "13850"},
    {"name": "NY CJ Ball Inc.", "address": "2520 Vestal Parkway, East Suite 2", "city": "Vestal", "zip": "13850"},
    {"name": "Flower City Dispensary Inc.", "address": "8047-8053 Pittsford-Victor Road", "city": "Victor", "zip": "14564"},
    {"name": "FingerLakes Cannabis Co.", "address": "5 Railroad St", "city": "Victor", "zip": "14564"},
    {"name": "CANNABIS DEPOT", "address": "23171 MURROCK CIRCLE", "city": "WATERTOWN", "zip": "13601"},
    {"name": "14707 45th LLC", "address": "844 Rt-211", "city": "Wallkill", "zip": "10941"},
    {"name": "Wappingers Cannabis LLC", "address": "1444 Route 9D", "city": "Wappinger", "zip": "12590"},
    {"name": "Hudson Strands", "address": "1839 South Rd", "city": "Wappingers Falls", "zip": "12590"},
    {"name": "Root 9 Dispensary", "address": "1546 Route 9", "city": "Wappingers Falls", "zip": "12590"},
    {"name": "Mileva LLC", "address": "3873 Main St", "city": "Warrensburg", "zip": "12885"},
    {"name": "A Classy Joint Cannabis, LLC", "address": "46 Ronald Reagan Blvd", "city": "Warwick", "zip": "10990"},
    {"name": "Ashley Capraro LLC", "address": "978 Montauk Hwy", "city": "Water Mill", "zip": "11976"},
    {"name": "Leafy Peaks", "address": "27B Saratoga Ave", "city": "Waterford", "zip": "12188"},
    {"name": "NTNR Dispensary LLC", "address": "332 Broad St", "city": "Waverly", "zip": "14892"},
    {"name": "Orange County Cannabis Co", "address": "1308 Dolsontown Rd Suite 3 & 4", "city": "Waywayanda", "zip": "10940"},
    {"name": "AB CANN LLC", "address": "111 Cabot St", "city": "West Babylon", "zip": "11704"},
    {"name": "Joyful Shores", "address": "108 Lamar St", "city": "West Babylon", "zip": "11704"},
    {"name": "Aromatic Gardens", "address": "231 Edison Ave", "city": "West Babylon", "zip": "11704"},
    {"name": "THE HIGH LIFE", "address": "1300 Wellwood Ave", "city": "West Babylon", "zip": "11704"},
    {"name": "Island Leaf LLC", "address": "9 Mahan Street", "city": "West Babylon", "zip": "11704"},
    {"name": "The Green Hut, LLC", "address": "12187 State Route 9W", "city": "West Coxsackie", "zip": "12192"},
    {"name": "Devil's Lettuce LLC", "address": "650 Orchard Park Rd", "city": "West Seneca", "zip": "14224"},
    {"name": "Green Philosophy 716 Inc.", "address": "101 Slade Ave", "city": "West Seneca", "zip": "14224"},
    {"name": "Daisy's Dispensary", "address": "6519 Main St Unit B", "city": "Westport", "zip": "12993"},
    {"name": "Amber Jane", "address": "1577 State Route 17B", "city": "White Lake", "zip": "12786"},
    {"name": "Cannabis Realm of New York", "address": "475 Central Ave", "city": "White Plains", "zip": "10606"},
    {"name": "Leafology Cannabis Company", "address": "244 Main St", "city": "White Plains", "zip": "10601"},
    {"name": "Fluent", "address": "75 Mamaroneck Avenue", "city": "White Plains", "zip": "10601"},
    {"name": "RSSQ Holding LLC", "address": "1200 Mamaroneck Ave", "city": "White Plains", "zip": "10605"},
    {"name": "Star Life Retail Group LLC", "address": "1 Hall Ave", "city": "White Plains", "zip": "10603"},
    {"name": "The purple owl Dispensary", "address": "405 Mamaroneck Ave", "city": "White Plains", "zip": "10605"},
    {"name": "THINC PROVISIONS INC", "address": "132 Broadway", "city": "Whitehall", "zip": "12887"},
    {"name": "Cannabis Group NY, LLC", "address": "14518 14th Ave", "city": "Whitestone", "zip": "11357"},
    {"name": "Flynnstoned Cannabis Company", "address": "6850 Main Street", "city": "Williamsville", "zip": "14221"},
    {"name": "The Coughie Shop Limited Liability Company", "address": "12044 E. MAIN STREET", "city": "Wolcott", "zip": "14590"},
    {"name": "Bay Bridge East LLC", "address": "95-31 Jamaica Ave", "city": "Woodhaven", "zip": "11421"},
    {"name": "KiKi Buddz Corp.", "address": "50-12 72nd Street", "city": "Woodside", "zip": "11377"},
    {"name": "Primary Care Group LLC", "address": "5806 Laurel Hill Blvd", "city": "Woodside", "zip": "11377"},
    {"name": "Plant Meets Public LLC", "address": "17 Tinker St", "city": "Woodstock", "zip": "12498"},
    {"name": "Woodstock Oasis", "address": "187 Kingston Ave", "city": "Wurstboro", "zip": "12790"},
    {"name": "10415 Jamaica LLC", "address": "1703 Central Park Avenue", "city": "Yonkers", "zip": "10710"},
    {"name": "AFI & Associates Group LLC", "address": "2371 Central Park Ave", "city": "Yonkers", "zip": "10710"},
    {"name": "Skones Dispensary", "address": "743 Central Park Ave", "city": "Yonkers", "zip": "10704"},
    {"name": "Budr Cannabis", "address": "887 Yonkers Ave", "city": "Yonkers", "zip": "10704"},
    {"name": "Cloud 9 Smoke & Gift Shop Inc.", "address": "305 Saw Mill River Rd", "city": "Yonkers", "zip": "10701"},
    {"name": "Green Zephyr, LLC", "address": "865-867 Mclean Ave", "city": "Yonkers", "zip": "10704"},
    {"name": "The Plant", "address": "2595 Central Park Ave", "city": "Yonkers", "zip": "10710"},
    {"name": "Polanco Brothers on the Hudson", "address": "8 Warburton Ave", "city": "Yonkers", "zip": "10701"},
    {"name": "Green Bar", "address": "471 McLean Ave", "city": "Yonkers", "zip": "10705"},
    {"name": "YONKERS DREAM LLC", "address": "2245 Central Park Ave", "city": "Yonkers", "zip": "10710"},
    {"name": "Yonkers Grown LLC", "address": "678 Central Park Ave", "city": "Yonkers", "zip": "10704"},
    {"name": "UPSTATENY CANNABIS, LLC", "address": "626 Oriskany Blvd", "city": "Yorkville", "zip": "13495"},
    {"name": "Higher Tolerance", "address": "121 south pearl street", "city": "albany", "zip": "12207"},
    {"name": "Whitstone LLC", "address": "50 old fulton st", "city": "brooklyn", "zip": "11201"},
    {"name": "THE WEED SHOPPE INC.", "address": "4906 Arthur Kill Road", "city": "staten island", "zip": "10309"},
    {"name": "Wee4justice 3", "address": "48 35 41 street", "city": "sunnyside", "zip": "11104"},
]
